// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitCustomerApi.Domain.Entities.Enums;

/// <summary>
/// Yapay zeka uretim isteginin turunu ifade eder.
/// </summary>
public enum AiRequestType
{
    /// <summary>
    /// Antrenman programi uretimi.
    /// </summary>
    Workout,
    /// <summary>
    /// Beslenme programi uretimi.
    /// </summary>
    Nutrition,
    /// <summary>
    /// Kisisel ic gorulama/analiz uretimi.
    /// </summary>
    Insight
}

/// <summary>
/// Yapay zeka uretim isteginin durumunu ifade eder.
/// </summary>
public enum AiGenerationStatus
{
    /// <summary>
    /// Istek beklemede.
    /// </summary>
    Pending,
    /// <summary>
    /// Istek isleniyor.
    /// </summary>
    Processing,
    /// <summary>
    /// Istek tamamlandi.
    /// </summary>
    Completed,
    /// <summary>
    /// Istek basarisiz oldu.
    /// </summary>
    Failed
}
