// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitCustomerApi.Domain.Entities.Enums;

/// <summary>
/// Liderlik tablosu doneminin turunu ifade eder.
/// </summary>
public enum LeaderboardPeriodType
{
    /// <summary>
    /// Haftalik donem.
    /// </summary>
    Weekly,
    /// <summary>
    /// Aylik donem.
    /// </summary>
    Monthly,
    /// <summary>
    /// Tum zamanlar donemi.
    /// </summary>
    AllTime
}

/// <summary>
/// Kullaniciya tanimlanan odulun durumunu ifade eder.
/// </summary>
public enum UserRewardStatus
{
    /// <summary>
    /// Odul beklemede.
    /// </summary>
    Pending,
    /// <summary>
    /// Odul talep edildi/teslim alindi.
    /// </summary>
    Claimed,
    /// <summary>
    /// Odulun suresi doldu.
    /// </summary>
    Expired,
    /// <summary>
    /// Odul iptal edildi.
    /// </summary>
    Cancelled
}
