// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitCustomerApi.Domain.Entities.Enums;

/// <summary>
/// Yasal belgenin turunu ifade eder.
/// </summary>
public enum LegalDocumentType
{
    /// <summary>
    /// Gizlilik politikasi.
    /// </summary>
    PrivacyPolicy,
    /// <summary>
    /// Kullanim kosullari.
    /// </summary>
    TermsOfService
}
