// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitCustomerApi.Domain.Entities.Enums;

/// <summary>
/// Bildirimin turunu ifade eder.
/// </summary>
public enum NotificationType
{
    /// <summary>
    /// Antrenman hatirlatma bildirimi.
    /// </summary>
    WorkoutReminder,
    /// <summary>
    /// Hedef hatirlatma bildirimi.
    /// </summary>
    GoalReminder,
    /// <summary>
    /// Seri (streak) hatirlatma bildirimi.
    /// </summary>
    StreakReminder,
    /// <summary>
    /// Ilerleme guncelleme bildirimi.
    /// </summary>
    ProgressUpdate,
    /// <summary>
    /// Liderlik tablosu guncelleme bildirimi.
    /// </summary>
    LeaderboardUpdate,
    /// <summary>
    /// Basari/rozet bildirimi.
    /// </summary>
    Achievement,
    /// <summary>
    /// Odul bildirimi.
    /// </summary>
    Reward,
    /// <summary>
    /// Abonelik ile ilgili bildirim.
    /// </summary>
    Subscription,
    /// <summary>
    /// Sistem bildirimi.
    /// </summary>
    System,
    /// <summary>
    /// Pazarlama amacli bildirim.
    /// </summary>
    Marketing
}
