// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitCustomerApi.Domain.Entities.Enums;

/// <summary>
/// Bir PersonalizationJob kaydinin uzerinde bulundugu asamayi ifade eder. Ileride eklenecek
/// arka plan islemcisi (workout/nutrition plan generator) bu durumlar arasinda gecis yapacaktir.
/// </summary>
public enum PersonalizationJobStatus
{
    /// <summary>Is henuz islenmeye baslanmadi; kuyrukta bekliyor.</summary>
    Pending,

    /// <summary>Is arka planda isleniyor.</summary>
    Processing,

    /// <summary>Is basariyla tamamlandi.</summary>
    Completed,

    /// <summary>Is islenirken hata olustu.</summary>
    Failed
}
