// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitCustomerApi.Domain.Entities.Enums;

/// <summary>
/// Abonelik odemesinin saglayicisini ifade eder.
/// </summary>
public enum SubscriptionProvider
{
    /// <summary>
    /// Apple App Store.
    /// </summary>
    Apple,
    /// <summary>
    /// Google Play Store.
    /// </summary>
    Google
}

/// <summary>
/// Abonelik urununun faturalama periyodunu ifade eder.
/// </summary>
public enum BillingPeriod
{
    /// <summary>
    /// Aylik faturalama.
    /// </summary>
    Monthly,
    /// <summary>
    /// Yillik faturalama.
    /// </summary>
    Yearly
}

/// <summary>
/// Abonelik durumunu ifade eder.
/// </summary>
public enum SubscriptionStatus
{
    /// <summary>
    /// Abonelik aktif.
    /// </summary>
    Active,
    /// <summary>
    /// Abonelik suresi dolmus.
    /// </summary>
    Expired,
    /// <summary>
    /// Abonelik iptal edilmis.
    /// </summary>
    Cancelled,
    /// <summary>
    /// Abonelik ucreti iade edilmis.
    /// </summary>
    Refunded,
    /// <summary>
    /// Abonelik duraklatilmis.
    /// </summary>
    Paused,
    /// <summary>
    /// Abonelik odeme yenileme icin ek surede.
    /// </summary>
    GracePeriod
}
