// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitCustomerApi.Domain.Entities.Enums;

/// <summary>
/// Destek talebinin durumunu ifade eder.
/// </summary>
public enum SupportTicketStatus
{
    /// <summary>
    /// Talep acik.
    /// </summary>
    Open,
    /// <summary>
    /// Talep uzerinde calisiliyor.
    /// </summary>
    InProgress,
    /// <summary>
    /// Talep cozuldu.
    /// </summary>
    Resolved,
    /// <summary>
    /// Talep kapatildi.
    /// </summary>
    Closed
}

/// <summary>
/// Destek talebinin oncelik seviyesini ifade eder.
/// </summary>
public enum SupportTicketPriority
{
    /// <summary>
    /// Dusuk oncelik.
    /// </summary>
    Low,
    /// <summary>
    /// Orta oncelik.
    /// </summary>
    Medium,
    /// <summary>
    /// Yuksek oncelik.
    /// </summary>
    High,
    /// <summary>
    /// Acil oncelik.
    /// </summary>
    Urgent
}
