// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitCustomerApi.Domain.Entities.Enums;

/// <summary>
/// Kullanicinin cinsiyetini ifade eder.
/// </summary>
public enum Gender
{
    /// <summary>
    /// Erkek.
    /// </summary>
    Male,
    /// <summary>
    /// Kadin.
    /// </summary>
    Female,
    /// <summary>
    /// Diger / belirtilmek istenmeyen.
    /// </summary>
    Other
}

/// <summary>
/// Kullanicinin fitness hedefini ifade eder.
/// </summary>
public enum FitnessGoal
{
    /// <summary>
    /// Kilo verme hedefi.
    /// </summary>
    LoseWeight,
    /// <summary>
    /// Kas kutlesi kazanma hedefi.
    /// </summary>
    BuildMuscle,
    /// <summary>
    /// Mevcut kiloyu koruma hedefi.
    /// </summary>
    MaintainWeight,
    /// <summary>
    /// Dayaniklilik gelistirme hedefi.
    /// </summary>
    ImproveEndurance,
    /// <summary>
    /// Guclenme hedefi.
    /// </summary>
    GetStronger,
    /// <summary>
    /// Genel fitness seviyesini gelistirme hedefi.
    /// </summary>
    ImproveFitness
}

/// <summary>
/// Kullanicinin antrenman deneyim seviyesini ifade eder.
/// </summary>
public enum ExperienceLevel
{
    /// <summary>
    /// Yeni baslayan.
    /// </summary>
    Beginner,
    /// <summary>
    /// Orta seviye.
    /// </summary>
    Intermediate,
    /// <summary>
    /// Ileri seviye.
    /// </summary>
    Advanced
}

/// <summary>
/// Kullanicinin gunluk aktivite seviyesini ifade eder.
/// </summary>
public enum ActivityLevel
{
    /// <summary>
    /// Hareketsiz yasam tarzi.
    /// </summary>
    Sedentary,
    /// <summary>
    /// Hafif duzeyde aktif.
    /// </summary>
    LightlyActive,
    /// <summary>
    /// Orta duzeyde aktif.
    /// </summary>
    ModeratelyActive,
    /// <summary>
    /// Yuksek duzeyde aktif.
    /// </summary>
    VeryActive,
    /// <summary>
    /// Cok yuksek duzeyde aktif.
    /// </summary>
    ExtraActive
}

/// <summary>
/// Kullanicinin antrenman yaptigi yeri ifade eder.
/// </summary>
public enum TrainingLocation
{
    /// <summary>
    /// Evde antrenman.
    /// </summary>
    Home,
    /// <summary>
    /// Spor salonunda antrenman.
    /// </summary>
    Gym,
    /// <summary>
    /// Acik havada antrenman.
    /// </summary>
    Outdoor
}

/// <summary>
/// Olcum biriminin sistemini ifade eder.
/// </summary>
public enum UnitSystem
{
    /// <summary>
    /// Metrik sistem (kg, cm).
    /// </summary>
    Metric,
    /// <summary>
    /// Imperial sistem (lb, inch).
    /// </summary>
    Imperial
}

/// <summary>
/// Uygulama gorunum temasini ifade eder.
/// </summary>
public enum Theme
{
    /// <summary>
    /// Acik tema.
    /// </summary>
    Light,
    /// <summary>
    /// Koyu tema.
    /// </summary>
    Dark,
    /// <summary>
    /// Cihaz sistem temasini takip eder.
    /// </summary>
    System
}

/// <summary>
/// Cihazin isletim sistemi platformunu ifade eder.
/// </summary>
public enum Platform
{
    /// <summary>
    /// Apple iOS platformu.
    /// </summary>
    IOS,
    /// <summary>
    /// Google Android platformu.
    /// </summary>
    Android,
    /// <summary>
    /// Web tarayici platformu.
    /// </summary>
    Web
}

/// <summary>
/// Kullanicinin sisteme erisim yetki seviyesini (rolunu) ifade eder.
/// JWT icerisine "role" claim'i olarak eklenir ve Admin API'nin
/// [Authorize(Policy = "AdminOnly")] kontrolunde kullanilir.
/// </summary>
public enum UserRole
{
    /// <summary>
    /// Standart mobil uygulama kullanicisi. Admin API'ye erisemez.
    /// </summary>
    User,
    /// <summary>
    /// Admin panelindeki operasyonel islemleri (icerik, kullanici, destek vb.) yonetebilen kullanici.
    /// </summary>
    Admin,
    /// <summary>
    /// Tum admin yetkilerine ek olarak sistem duzeyinde hassas islemleri yapabilen ust duzey yonetici.
    /// </summary>
    SuperAdmin
}
