// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitCustomerApi.Domain.Entities.Enums;

/// <summary>
/// Antrenman veya egzersizin zorluk seviyesini ifade eder.
/// </summary>
public enum DifficultyLevel
{
    /// <summary>
    /// Baslangic seviyesi.
    /// </summary>
    Beginner,
    /// <summary>
    /// Orta seviye.
    /// </summary>
    Intermediate,
    /// <summary>
    /// Ileri seviye.
    /// </summary>
    Advanced
}

/// <summary>
/// Bir antrenman oturumunun durumunu ifade eder.
/// </summary>
public enum WorkoutSessionStatus
{
    /// <summary>
    /// Oturum baslatildi.
    /// </summary>
    Started,
    /// <summary>
    /// Oturum duraklatildi.
    /// </summary>
    Paused,
    /// <summary>
    /// Oturum tamamlandi.
    /// </summary>
    Completed,
    /// <summary>
    /// Oturum iptal edildi.
    /// </summary>
    Cancelled,
    /// <summary>
    /// Oturum yarim birakildi.
    /// </summary>
    Abandoned
}
