// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Achievement varligini temsil eder.
/// </summary>
public class Achievement : BaseEntity
{
    /// <summary>
    /// Basarinin sistemsel kodu (orn. FIRST_WORKOUT).
    /// </summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Basarinin baslikta gosterilen adi.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Basarinin aciklamasi.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Basari icin kullanilan ikon/gorsel adresi.
    /// </summary>
    public string? Icon { get; set; }

    /// <summary>
    /// Basarinin kazandirdigi puan.
    /// </summary>
    public int Points { get; set; }

    /// <summary>
    /// Basarinin kazanilma kosulunun turu.
    /// </summary>
    public string ConditionType { get; set; } = string.Empty;

    /// <summary>
    /// Basarinin kazanilma kosuluna ait deger.
    /// </summary>
    public string ConditionValue { get; set; } = string.Empty;

    /// <summary>
    /// Basarinin aktif/yayinda olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }
}
