// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// AiGenerationResult varligini temsil eder.
/// </summary>
public class AiGenerationResult : BaseEntity
{
    /// <summary>
    /// Iliskili uretim istegi kimligi.
    /// </summary>
    public long RequestId { get; set; }

    /// <summary>
    /// Uretilen sonucun JSON formatinda tutuldugu alan.
    /// </summary>
    public string ResultJson { get; set; } = string.Empty;
}
