// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// AppContent varligini temsil eder.
/// </summary>
public class AppContent : BaseEntity
{
    /// <summary>
    /// Icerigin sistemsel anahtari (orn. home.banner).
    /// </summary>
    public string Key { get; set; } = string.Empty;

    /// <summary>
    /// Icerigin turu.
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// Icerigin basligi.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Icerigin aciklamasi.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Icerik gorselinin adresi.
    /// </summary>
    public string? ImageUrl { get; set; }

    /// <summary>
    /// Icerigin yonlendirdigi baglanti adresi.
    /// </summary>
    public string? LinkUrl { get; set; }

    /// <summary>
    /// Icerigin aktif/yayinda olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Icerigin yayina baslama tarihi.
    /// </summary>
    public DateTime? StartAt { get; set; }

    /// <summary>
    /// Icerigin yayindan kaldirilma tarihi.
    /// </summary>
    public DateTime? EndAt { get; set; }
}
