// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// ApplicationUser varligini temsil eder.
/// </summary>
public class ApplicationUser : BaseEntity
{
    /// <summary>
    /// Kullanicinin e-posta adresi.
    /// </summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// Karsilastirma icin normallestirilmis (buyuk harfe cevrilmis) e-posta adresi.
    /// </summary>
    public string NormalizedEmail { get; set; } = string.Empty;

    /// <summary>
    /// Kullanicinin kullanici adi.
    /// </summary>
    public string UserName { get; set; } = string.Empty;

    /// <summary>
    /// Karsilastirma icin normallestirilmis kullanici adi.
    /// </summary>
    public string NormalizedUserName { get; set; } = string.Empty;

    /// <summary>
    /// Kullanicinin sifrelenmis (hash'lenmis) parolasi.
    /// </summary>
    public string PasswordHash { get; set; } = string.Empty;

    /// <summary>
    /// Kullanicinin telefon numarasi.
    /// </summary>
    public string? PhoneNumber { get; set; }

    /// <summary>
    /// E-posta adresinin dogrulanip dogrulanmadigi.
    /// </summary>
    public bool EmailConfirmed { get; set; }

    /// <summary>
    /// Telefon numarasinin dogrulanip dogrulanmadigi.
    /// </summary>
    public bool PhoneNumberConfirmed { get; set; }

    /// <summary>
    /// Hesap kilitleme ozelliginin aktif olup olmadigi.
    /// </summary>
    public bool LockoutEnabled { get; set; }

    /// <summary>
    /// Kullanici hesabinin aktif olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Kullanicinin yetki seviyesi (User/Admin/SuperAdmin). JWT "role" claim'ine yazilir ve
    /// Admin API'nin [Authorize(Policy = "AdminOnly")] kontrolu bu alana gore calisir.
    /// Varsayilan olarak tum yeni kayitlar "User" rolundedir; admin kullanicilar veritabaninda
    /// veya ileride eklenecek bir "promote to admin" akisiyla elle atanir.
    /// </summary>
    public UserRole Role { get; set; } = UserRole.User;

    /// <summary>
    /// Kullanicinin son giris yaptigi tarih.
    /// </summary>
    public DateTime? LastLoginAt { get; set; }

    /// <summary>
    /// Kullanicinin (varsa) silindigi tarih; soft-delete icin kullanilir.
    /// </summary>
    public DateTime? DeletedAt { get; set; }
}
