// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;
using System.Text.Json;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// AuditLog varligini temsil eder.
/// </summary>
public class AuditLog : BaseEntity
{
    /// <summary>
    /// Islemi gerceklestiren kullanicinin kimligi.
    /// </summary>
    public long? UserId { get; set; }

    /// <summary>
    /// Gerceklesen islemin adi (orn. LOGIN, PASSWORD_CHANGED).
    /// </summary>
    public string Action { get; set; } = string.Empty;

    /// <summary>
    /// Islemin ilgili oldugu varlik adi.
    /// </summary>
    public string Entity { get; set; } = string.Empty;

    /// <summary>
    /// Islemin ilgili oldugu varlik kimligi.
    /// </summary>
    public long? EntityId { get; set; }

    /// <summary>
    /// Islemin gerceklestigi IP adresi.
    /// </summary>
    public string? IpAddress { get; set; }

    /// <summary>
    /// Islemin gerceklestigi istemci bilgisi (user agent).
    /// </summary>
    public string? UserAgent { get; set; }

    /// <summary>
    /// Isleme dair ek verilerin JSON formatinda tutuldugu alan.
    /// </summary>
    public JsonDocument? MetadataJson { get; set; }
}
