// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Equipment varligini temsil eder.
/// </summary>
public class Equipment : BaseEntity
{
    /// <summary>
    /// Ekipmanin adi (orn. Dambil, Halter).
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Ekipmanin URL dostu kisa adi.
    /// </summary>
    public string Slug { get; set; } = string.Empty;
}
