// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Exercise varligini temsil eder.
/// </summary>
public class Exercise : BaseEntity
{
    /// <summary>
    /// Egzersizin adi.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Egzersizin URL dostu kisa adi.
    /// </summary>
    public string Slug { get; set; } = string.Empty;

    /// <summary>
    /// Egzersizin genel aciklamasi.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Egzersizin nasil yapilacagina dair adim adim talimatlar.
    /// </summary>
    public string? Instructions { get; set; }

    /// <summary>
    /// Egzersizin zorluk seviyesi.
    /// </summary>
    public DifficultyLevel Difficulty { get; set; }

    /// <summary>
    /// Egzersizin hedefledigi ana kas grubunun kimligi.
    /// </summary>
    public long PrimaryMuscleGroupId { get; set; }

    /// <summary>
    /// Egzersiz icin gereken ekipman turunu belirten serbest metin.
    /// </summary>
    public string? EquipmentType { get; set; }

    /// <summary>
    /// Egzersiz anlatim videosunun adresi.
    /// </summary>
    public string? VideoUrl { get; set; }

    /// <summary>
    /// Egzersiz gorselinin adresi.
    /// </summary>
    public string? ImageUrl { get; set; }

    /// <summary>
    /// Egzersizin dakika basina yaktigi tahmini kalori.
    /// </summary>
    public decimal? CaloriesPerMinute { get; set; }

    /// <summary>
    /// Egzersizin aktif/yayinda olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }
}
