// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// FAQCategory varligini temsil eder.
/// </summary>
public class FAQCategory : BaseEntity
{
    /// <summary>
    /// Kategorinin adi.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Kategorinin listelenme sirasi.
    /// </summary>
    public int SortOrder { get; set; }
}
