// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Feature varligini temsil eder.
/// </summary>
public class Feature : BaseEntity
{
    /// <summary>
    /// Ozelligin sistemsel kodu (orn. AI_WORKOUT).
    /// </summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Ozelligin adi.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Ozelligin aciklamasi.
    /// </summary>
    public string? Description { get; set; }
}
