// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Food varligini temsil eder.
/// </summary>
public class Food : BaseEntity
{
    /// <summary>
    /// Besinin adi.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Besinin barkod numarasi.
    /// </summary>
    public string? Barcode { get; set; }

    /// <summary>
    /// Besinin markasi.
    /// </summary>
    public string? Brand { get; set; }

    /// <summary>
    /// Referans porsiyon miktari.
    /// </summary>
    public decimal ServingSize { get; set; }

    /// <summary>
    /// Porsiyon birimi (orn. gram, ml, adet).
    /// </summary>
    public string ServingUnit { get; set; } = string.Empty;

    /// <summary>
    /// Porsiyon basina kalori miktari.
    /// </summary>
    public decimal Calories { get; set; }

    /// <summary>
    /// Porsiyon basina protein miktari (gram).
    /// </summary>
    public decimal Protein { get; set; }

    /// <summary>
    /// Porsiyon basina karbonhidrat miktari (gram).
    /// </summary>
    public decimal Carbs { get; set; }

    /// <summary>
    /// Porsiyon basina yag miktari (gram).
    /// </summary>
    public decimal Fat { get; set; }

    /// <summary>
    /// Porsiyon basina lif miktari (gram).
    /// </summary>
    public decimal? Fiber { get; set; }

    /// <summary>
    /// Porsiyon basina seker miktari (gram).
    /// </summary>
    public decimal? Sugar { get; set; }

    /// <summary>
    /// Porsiyon basina sodyum miktari (miligram).
    /// </summary>
    public decimal? Sodium { get; set; }

    /// <summary>
    /// Besin gorselinin adresi.
    /// </summary>
    public string? ImageUrl { get; set; }
}
