// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Language varligini temsil eder.
/// </summary>
public class Language : BaseEntity
{
    /// <summary>
    /// Dilin ISO koduna (orn. tr, en) karsilik gelen degeri.
    /// </summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Dilin adi.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Dilin varsayilan dil olup olmadigi.
    /// </summary>
    public bool IsDefault { get; set; }

    /// <summary>
    /// Dilin aktif olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }
}
