// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// LegalDocument varligini temsil eder.
/// </summary>
public class LegalDocument : BaseEntity
{
    /// <summary>
    /// Belgenin turu.
    /// </summary>
    public LegalDocumentType Type { get; set; }

    /// <summary>
    /// Belgenin surum numarasi.
    /// </summary>
    public string Version { get; set; } = string.Empty;

    /// <summary>
    /// Belgenin diline ait kod.
    /// </summary>
    public string Language { get; set; } = string.Empty;

    /// <summary>
    /// Belgenin basligi.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Belgenin icerik metni.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Belgenin yayinlanma tarihi.
    /// </summary>
    public DateTime PublishedAt { get; set; }

    /// <summary>
    /// Belgenin guncel/yururlukte olan surum olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }
}
