// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Meal varligini temsil eder.
/// </summary>
public class Meal : BaseEntity
{
    /// <summary>
    /// Ogunu kaydeden kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Ogunun tuketildigi tarih.
    /// </summary>
    public DateTime Date { get; set; }

    /// <summary>
    /// Ogunun turu (kahvalti, ogle, aksam, ara ogun).
    /// </summary>
    public MealType MealType { get; set; }

    /// <summary>
    /// Oguna ait notlar.
    /// </summary>
    public string? Notes { get; set; }
}
