// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// MealItem varligini temsil eder.
/// </summary>
public class MealItem : BaseEntity
{
    /// <summary>
    /// Iliskili ogunun kimligi.
    /// </summary>
    public long MealId { get; set; }

    /// <summary>
    /// Iliskili besinin kimligi.
    /// </summary>
    public long FoodId { get; set; }

    /// <summary>
    /// Tuketilen miktar.
    /// </summary>
    public decimal Quantity { get; set; }

    /// <summary>
    /// Kayit anindaki porsiyon buyuklugu (anlik goruntu).
    /// </summary>
    public decimal ServingSize { get; set; }

    /// <summary>
    /// Kayit anindaki kalori miktari (anlik goruntu).
    /// </summary>
    public decimal Calories { get; set; }

    /// <summary>
    /// Kayit anindaki protein miktari (anlik goruntu).
    /// </summary>
    public decimal Protein { get; set; }

    /// <summary>
    /// Kayit anindaki karbonhidrat miktari (anlik goruntu).
    /// </summary>
    public decimal Carbs { get; set; }

    /// <summary>
    /// Kayit anindaki yag miktari (anlik goruntu).
    /// </summary>
    public decimal Fat { get; set; }

    /// <summary>
    /// Kayit anindaki lif miktari (anlik goruntu).
    /// </summary>
    public decimal? Fiber { get; set; }
}
