// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// MerfitScoreBreakdown varligini temsil eder.
/// </summary>
public class MerfitScoreBreakdown : BaseEntity
{
    /// <summary>
    /// Iliskili Merfit skorunun kimligi.
    /// </summary>
    public long MerfitScoreId { get; set; }

    /// <summary>
    /// Skor kaleminin kategorisi (orn. Consistency, Workouts).
    /// </summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// Bu kategoriden kazanilan puan.
    /// </summary>
    public decimal Points { get; set; }
}
