// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// MerfitScore varligini temsil eder.
/// </summary>
public class MerfitScore : BaseEntity
{
    /// <summary>
    /// Skorun ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Hesaplanan toplam skor degeri.
    /// </summary>
    public decimal Score { get; set; }

    /// <summary>
    /// Skorun hesaplandigi donemi ifade eden deger.
    /// </summary>
    public string Period { get; set; } = string.Empty;

    /// <summary>
    /// Skorun hesaplandigi tarih.
    /// </summary>
    public DateTime CalculatedAt { get; set; }
}
