// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// NutritionGoal varligini temsil eder.
/// </summary>
public class NutritionGoal : BaseEntity
{
    /// <summary>
    /// Hedefin ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Gunluk hedeflenen kalori miktari.
    /// </summary>
    public decimal DailyCalories { get; set; }

    /// <summary>
    /// Gunluk hedeflenen protein miktari (gram).
    /// </summary>
    public decimal ProteinTarget { get; set; }

    /// <summary>
    /// Gunluk hedeflenen karbonhidrat miktari (gram).
    /// </summary>
    public decimal CarbsTarget { get; set; }

    /// <summary>
    /// Gunluk hedeflenen yag miktari (gram).
    /// </summary>
    public decimal FatTarget { get; set; }

    /// <summary>
    /// Gunluk hedeflenen su miktari (mililitre).
    /// </summary>
    public decimal WaterTargetMl { get; set; }
}
