// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// PersonalRecord varligini temsil eder.
/// </summary>
public class PersonalRecord : BaseEntity
{
    /// <summary>
    /// Rekoru kiran kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Rekorun ait oldugu egzersizin kimligi.
    /// </summary>
    public long ExerciseId { get; set; }

    /// <summary>
    /// Rekor sirasinda kaldirilan agirlik (kilogram).
    /// </summary>
    public decimal WeightKg { get; set; }

    /// <summary>
    /// Rekor sirasinda yapilan tekrar sayisi.
    /// </summary>
    public int Reps { get; set; }

    /// <summary>
    /// Hesaplanan tahmini bir tekrar maksimumu (1RM).
    /// </summary>
    public decimal EstimatedOneRepMax { get; set; }

    /// <summary>
    /// Rekorun kirildigi tarih.
    /// </summary>
    public DateTime AchievedAt { get; set; }

    /// <summary>
    /// Rekorun kirildigi antrenman oturumunun kimligi.
    /// </summary>
    public long? WorkoutSessionId { get; set; }
}
