// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Reward varligini temsil eder.
/// </summary>
public class Reward : BaseEntity
{
    /// <summary>
    /// Odulun basligi.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Odulun aciklamasi.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Odul gorselinin adresi.
    /// </summary>
    public string? ImageUrl { get; set; }

    /// <summary>
    /// Odulun turu (orn. watch, premium, bag).
    /// </summary>
    public string RewardType { get; set; } = string.Empty;

    /// <summary>
    /// Odule ait deger/detay bilgisi.
    /// </summary>
    public string? Value { get; set; }

    /// <summary>
    /// Odulun aktif/gecerli olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }
}
