// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Subscription varligini temsil eder.
/// </summary>
public class Subscription : BaseEntity
{
    /// <summary>
    /// Abonelik sahibi kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Satin alinan abonelik urununun kimligi.
    /// </summary>
    public long SubscriptionProductId { get; set; }

    /// <summary>
    /// Odemenin gerceklestigi magaza saglayicisi.
    /// </summary>
    public SubscriptionProvider Provider { get; set; }

    /// <summary>
    /// Magaza tarafindaki islem kimligi.
    /// </summary>
    public string? ExternalTransactionId { get; set; }

    /// <summary>
    /// Abonelik durumu.
    /// </summary>
    public SubscriptionStatus Status { get; set; }

    /// <summary>
    /// Aboneligin baslangic tarihi.
    /// </summary>
    public DateTime StartedAt { get; set; }

    /// <summary>
    /// Aboneligin son gecerlilik tarihi.
    /// </summary>
    public DateTime? ExpiresAt { get; set; }

    /// <summary>
    /// Aboneligin otomatik yenilenip yenilenmeyecegi.
    /// </summary>
    public bool AutoRenew { get; set; }

    /// <summary>
    /// Aboneligin iptal edildigi tarih.
    /// </summary>
    public DateTime? CancelledAt { get; set; }
}
