// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// SubscriptionProduct varligini temsil eder.
/// </summary>
public class SubscriptionProduct : BaseEntity
{
    /// <summary>
    /// Urunun sistemsel kodu (orn. MERFIT_PLUS_MONTHLY).
    /// </summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Urunun adi.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// App Store urun kimligi.
    /// </summary>
    public string? StoreProductIdIos { get; set; }

    /// <summary>
    /// Google Play urun kimligi.
    /// </summary>
    public string? StoreProductIdAndroid { get; set; }

    /// <summary>
    /// Urunun faturalama periyodu.
    /// </summary>
    public BillingPeriod BillingPeriod { get; set; }

    /// <summary>
    /// Urunun fiyati.
    /// </summary>
    public decimal Price { get; set; }

    /// <summary>
    /// Fiyatin para birimi.
    /// </summary>
    public string Currency { get; set; } = string.Empty;

    /// <summary>
    /// Urunun aktif/satista olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }
}
