// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// SubscriptionPlanFeature varligini temsil eder.
/// </summary>
public class SubscriptionPlanFeature : BaseEntity
{
    /// <summary>
    /// Iliskili abonelik urununun kimligi.
    /// </summary>
    public long SubscriptionProductId { get; set; }

    /// <summary>
    /// Iliskili ozelligin kimligi.
    /// </summary>
    public long FeatureId { get; set; }
}
