// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// SubscriptionTransaction varligini temsil eder.
/// </summary>
public class SubscriptionTransaction : BaseEntity
{
    /// <summary>
    /// Iliskili aboneligin kimligi.
    /// </summary>
    public long SubscriptionId { get; set; }

    /// <summary>
    /// Islemin gerceklestigi magaza saglayicisi.
    /// </summary>
    public SubscriptionProvider Provider { get; set; }

    /// <summary>
    /// Magaza tarafindaki benzersiz islem kimligi.
    /// </summary>
    public string TransactionId { get; set; } = string.Empty;

    /// <summary>
    /// Yenilemelerde referans olan ilk islem kimligi.
    /// </summary>
    public string? OriginalTransactionId { get; set; }

    /// <summary>
    /// Magazadaki urun kimligi.
    /// </summary>
    public string ProductId { get; set; } = string.Empty;

    /// <summary>
    /// Islem tutari.
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Islemin para birimi.
    /// </summary>
    public string Currency { get; set; } = string.Empty;

    /// <summary>
    /// Satin alma tarihi.
    /// </summary>
    public DateTime PurchasedAt { get; set; }

    /// <summary>
    /// Islemin gecerlilik bitis tarihi.
    /// </summary>
    public DateTime? ExpiresAt { get; set; }

    /// <summary>
    /// Magazadan alinan ham makbuz verisi.
    /// </summary>
    public string? RawReceipt { get; set; }
}
