// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Translation varligini temsil eder.
/// </summary>
public class Translation : BaseEntity
{
    /// <summary>
    /// Iliskili dilin kimligi.
    /// </summary>
    public long LanguageId { get; set; }

    /// <summary>
    /// Ceviri metnine karsilik gelen anahtar (orn. workout.start).
    /// </summary>
    public string ResourceKey { get; set; } = string.Empty;

    /// <summary>
    /// Anahtara karsilik gelen cevrilmis metin.
    /// </summary>
    public string Value { get; set; } = string.Empty;
}
