// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// UserStreak varligini temsil eder.
/// </summary>
public class UserStreak : BaseEntity
{
    /// <summary>
    /// Serinin ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Kullanicinin guncel ardisik gun sayisi.
    /// </summary>
    public int CurrentStreak { get; set; }

    /// <summary>
    /// Kullanicinin en uzun ardisik gun serisi.
    /// </summary>
    public int LongestStreak { get; set; }

    /// <summary>
    /// Son aktivite tarihi.
    /// </summary>
    public DateTime? LastActivityDate { get; set; }
}
