// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// UserProfile varligini temsil eder.
/// </summary>
public class UserProfile : BaseEntity
{
    /// <summary>
    /// Profilin ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Kullanicinin adi.
    /// </summary>
    public string FirstName { get; set; } = string.Empty;

    /// <summary>
    /// Kullanicinin soyadi.
    /// </summary>
    public string LastName { get; set; } = string.Empty;

    /// <summary>
    /// Profilde gosterilen kullanici adi.
    /// </summary>
    public string Username { get; set; } = string.Empty;

    /// <summary>
    /// Kullanicinin dogum tarihi.
    /// </summary>
    public DateTime? DateOfBirth { get; set; }

    /// <summary>
    /// Kullanicinin cinsiyeti.
    /// </summary>
    public Gender? Gender { get; set; }

    /// <summary>
    /// Kullanicinin boyu (santimetre).
    /// </summary>
    public decimal? HeightCm { get; set; }

    /// <summary>
    /// Kullanicinin guncel kilosu (kilogram).
    /// </summary>
    public decimal? WeightKg { get; set; }

    /// <summary>
    /// Kullanicinin hedefledigi kilo (kilogram).
    /// </summary>
    public decimal? TargetWeightKg { get; set; }

    /// <summary>
    /// Profil fotografinin adresi.
    /// </summary>
    public string? ProfileImageUrl { get; set; }

    /// <summary>
    /// Kullanicinin genel fitness hedefi.
    /// </summary>
    public FitnessGoal? Goal { get; set; }

    /// <summary>
    /// Kullanicinin antrenman deneyim seviyesi.
    /// </summary>
    public ExperienceLevel? ExperienceLevel { get; set; }

    /// <summary>
    /// Kullanicinin tercih ettigi antrenman suresi (dakika).
    /// </summary>
    public int? WorkoutDurationMin { get; set; }

    /// <summary>
    /// Kullanicinin gunluk aktivite seviyesi.
    /// </summary>
    public ActivityLevel? ActivityLevel { get; set; }

    /// <summary>
    /// Kullanicinin antrenman yaptigi ortam.
    /// </summary>
    public TrainingLocation? TrainingLocation { get; set; }

    /// <summary>
    /// Kullanicinin haftada kac gun antrenman yaptigi.
    /// </summary>
    public int? TrainingDaysPerWeek { get; set; }

    /// <summary>
    /// Kullanicinin tercih ettigi olcum birimi sistemi.
    /// </summary>
    public UnitSystem UnitSystem { get; set; }
}
