// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// UserPrivacySetting varligini temsil eder.
/// </summary>
public class UserPrivacySetting : BaseEntity
{
    /// <summary>
    /// Ayarin ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Profilin liderlik tablosunda gorunur olup olmadigi.
    /// </summary>
    public bool ProfileVisibleOnLeaderboard { get; set; }

    /// <summary>
    /// Antrenman istatistiklerinin paylasilip paylasilmadigi.
    /// </summary>
    public bool ShareWorkoutStatistics { get; set; }

    /// <summary>
    /// Kisisellestirilmis onerilerin acik olup olmadigi.
    /// </summary>
    public bool PersonalizedRecommendations { get; set; }
}
