// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// UserDevice varligini temsil eder.
/// </summary>
public class UserDevice : BaseEntity
{
    /// <summary>
    /// Cihazin ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Push bildirimleri icin cihaz jetonu.
    /// </summary>
    public string DeviceToken { get; set; } = string.Empty;

    /// <summary>
    /// Cihazin isletim sistemi platformu.
    /// </summary>
    public Platform Platform { get; set; }

    /// <summary>
    /// Cihazin adi.
    /// </summary>
    public string? DeviceName { get; set; }

    /// <summary>
    /// Cihazda yuklu uygulama surumu.
    /// </summary>
    public string? AppVersion { get; set; }

    /// <summary>
    /// Cihazin isletim sistemi surumu.
    /// </summary>
    public string? OsVersion { get; set; }

    /// <summary>
    /// Cihazin aktif olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Cihazin son gorulme tarihi.
    /// </summary>
    public DateTime? LastSeenAt { get; set; }
}
