// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// UserNotificationSetting varligini temsil eder.
/// </summary>
public class UserNotificationSetting : BaseEntity
{
    /// <summary>
    /// Ayarin ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Antrenman hatirlatma bildirimlerinin acik olup olmadigi.
    /// </summary>
    public bool WorkoutReminders { get; set; }

    /// <summary>
    /// Gunluk hedef hatirlatma bildiriminin acik olup olmadigi.
    /// </summary>
    public bool DailyGoalReminder { get; set; }

    /// <summary>
    /// Seri (streak) hatirlatma bildiriminin acik olup olmadigi.
    /// </summary>
    public bool StreakReminder { get; set; }

    /// <summary>
    /// Ilerleme guncelleme bildirimlerinin acik olup olmadigi.
    /// </summary>
    public bool ProgressUpdates { get; set; }

    /// <summary>
    /// Liderlik tablosu bildirimlerinin acik olup olmadigi.
    /// </summary>
    public bool LeaderboardUpdates { get; set; }

    /// <summary>
    /// Urun guncelleme bildirimlerinin acik olup olmadigi.
    /// </summary>
    public bool ProductUpdates { get; set; }
}
