// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// UserAchievement varligini temsil eder.
/// </summary>
public class UserAchievement : BaseEntity
{
    /// <summary>
    /// Basariyi kazanan kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Kazanilan basarinin kimligi.
    /// </summary>
    public long AchievementId { get; set; }

    /// <summary>
    /// Basarinin kazanildigi tarih.
    /// </summary>
    public DateTime EarnedAt { get; set; }
}
