// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// UserRefreshToken varligini temsil eder.
/// </summary>
public class UserRefreshToken : BaseEntity
{
    /// <summary>
    /// Jetonun ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Yenileme jetonunun degeri.
    /// </summary>
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// Jetonun son gecerlilik tarihi.
    /// </summary>
    public DateTime ExpiresAt { get; set; }

    /// <summary>
    /// Jetonun iptal edildigi tarih.
    /// </summary>
    public DateTime? RevokedAt { get; set; }

    /// <summary>
    /// Jetonun olusturuldugu IP adresi.
    /// </summary>
    public string? CreatedByIp { get; set; }

    /// <summary>
    /// Jetonun iptal edildigi IP adresi.
    /// </summary>
    public string? RevokedByIp { get; set; }

    /// <summary>
    /// Bu jetonun yerine gecen yeni jeton degeri.
    /// </summary>
    public string? ReplacementToken { get; set; }

    /// <summary>
    /// Jetonun iptal edilip edilmedigi.
    /// </summary>
    public bool IsRevoked { get; set; }

    /// <summary>
    /// Jetonun kullanilip kullanilmadigi.
    /// </summary>
    public bool IsUsed { get; set; }
}
