// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// UserPreference varligini temsil eder.
/// </summary>
public class UserPreference : BaseEntity
{
    /// <summary>
    /// Tercihin ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Kullanicinin tercih ettigi uygulama dili.
    /// </summary>
    public string Language { get; set; } = string.Empty;

    /// <summary>
    /// Kullanicinin tercih ettigi gorunum temasi.
    /// </summary>
    public Theme Theme { get; set; }

    /// <summary>
    /// Kullanicinin tercih ettigi olcum birimi sistemi.
    /// </summary>
    public UnitSystem UnitSystem { get; set; }
}
