// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// UserConsent varligini temsil eder.
/// </summary>
public class UserConsent : BaseEntity
{
    /// <summary>
    /// Onayi veren kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Onaylanan yasal belgenin kimligi.
    /// </summary>
    public long DocumentId { get; set; }

    /// <summary>
    /// Belgenin kabul edilip edilmedigi.
    /// </summary>
    public bool Accepted { get; set; }

    /// <summary>
    /// Belgenin kabul edildigi tarih.
    /// </summary>
    public DateTime AcceptedAt { get; set; }

    /// <summary>
    /// Onayin verildigi IP adresi.
    /// </summary>
    public string? IpAddress { get; set; }

    /// <summary>
    /// Onaylanan belge surumu.
    /// </summary>
    public string Version { get; set; } = string.Empty;
}
