// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// UserReward varligini temsil eder.
/// </summary>
public class UserReward : BaseEntity
{
    /// <summary>
    /// Odulu kazanan kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Kazanilan odulun kimligi.
    /// </summary>
    public long RewardId { get; set; }

    /// <summary>
    /// Odulun kazanildigi liderlik donemi kimligi.
    /// </summary>
    public long? LeaderboardPeriodId { get; set; }

    /// <summary>
    /// Odulun kazanildigi sirlama.
    /// </summary>
    public int? Rank { get; set; }

    /// <summary>
    /// Odulun guncel durumu.
    /// </summary>
    public UserRewardStatus Status { get; set; }

    /// <summary>
    /// Odulun teslim alindigi tarih.
    /// </summary>
    public DateTime? ClaimedAt { get; set; }
}
