// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// WaterLog varligini temsil eder.
/// </summary>
public class WaterLog : BaseEntity
{
    /// <summary>
    /// Kaydi olusturan kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Su tuketiminin gerceklestigi tarih.
    /// </summary>
    public DateTime Date { get; set; }

    /// <summary>
    /// Tuketilen su miktari (mililitre).
    /// </summary>
    public decimal AmountMl { get; set; }
}
