// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// WorkoutCategory varligini temsil eder.
/// </summary>
public class WorkoutCategory : BaseEntity
{
    /// <summary>
    /// Kategorinin adi (orn. Strength, Cardio).
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Kategorinin URL dostu kisa adi.
    /// </summary>
    public string Slug { get; set; } = string.Empty;

    /// <summary>
    /// Kategorinin aciklamasi.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Kategori gorselinin adresi.
    /// </summary>
    public string? ImageUrl { get; set; }

    /// <summary>
    /// Kategorinin aktif/yayinda olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }
}
