// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// WorkoutSession varligini temsil eder.
/// </summary>
public class WorkoutSession : BaseEntity
{
    /// <summary>
    /// Oturumu gerceklestiren kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Gerceklestirilen antrenmanin kimligi.
    /// </summary>
    public long WorkoutId { get; set; }

    /// <summary>
    /// Oturum kisisellestirilmis bir plan gununden baslatildiysa, ilgili WorkoutPlanDay'in
    /// kimligi; genel katalogdan (Workout Catalog) baslatilan oturumlarda null'dur. Doluysa,
    /// oturumdaki hedef set/tekrar/dinlenme degerleri WorkoutExercise yerine bu gune ait
    /// WorkoutPlanExercise kayitlarindan okunur.
    /// </summary>
    public long? WorkoutPlanDayId { get; set; }

    /// <summary>
    /// Oturumun baslangic tarihi/saati.
    /// </summary>
    public DateTime StartedAt { get; set; }

    /// <summary>
    /// Oturumun tamamlanma tarihi/saati.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Oturumun guncel durumu.
    /// </summary>
    public WorkoutSessionStatus Status { get; set; }

    /// <summary>
    /// Oturumun toplam suresi (saniye).
    /// </summary>
    public int? DurationSeconds { get; set; }

    /// <summary>
    /// Oturumda yakilan tahmini kalori.
    /// </summary>
    public decimal? CaloriesBurned { get; set; }

    /// <summary>
    /// Oturuma ait notlar.
    /// </summary>
    public string? Notes { get; set; }
}
