// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// WorkoutExercise varligini temsil eder.
/// </summary>
public class WorkoutExercise : BaseEntity
{
    /// <summary>
    /// Iliskili antrenmanin kimligi.
    /// </summary>
    public long WorkoutId { get; set; }

    /// <summary>
    /// Iliskili egzersizin kimligi.
    /// </summary>
    public long ExerciseId { get; set; }

    /// <summary>
    /// Egzersizin antrenman icindeki sirasi.
    /// </summary>
    public int Order { get; set; }

    /// <summary>
    /// Bu antrenmandaki set sayisi.
    /// </summary>
    public int Sets { get; set; }

    /// <summary>
    /// Set basina hedeflenen tekrar sayisi.
    /// </summary>
    public int? Reps { get; set; }

    /// <summary>
    /// Setler arasi dinlenme suresi (saniye).
    /// </summary>
    public int? RestSeconds { get; set; }

    /// <summary>
    /// Sureye dayali egzersizler icin hedef sure (saniye).
    /// </summary>
    public int? DurationSeconds { get; set; }

    /// <summary>
    /// Egzersize ozel notlar.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Egzersizin opsiyonel olup olmadigi.
    /// </summary>
    public bool IsOptional { get; set; }
}
