// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// WorkoutPlan varligini temsil eder.
/// </summary>
public class WorkoutPlan : BaseEntity
{
    /// <summary>
    /// Planin ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Planin adi.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Planin aciklamasi.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Planin hedefledigi fitness hedefi.
    /// </summary>
    public FitnessGoal? Goal { get; set; }

    /// <summary>
    /// Planin baslangic tarihi.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// Planin bitis tarihi.
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Planin aktif olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Planin yapay zeka tarafindan uretilip uretilmedigi.
    /// </summary>
    public bool IsAiGenerated { get; set; }
}
