// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Entities.Enums;
using MerfitCustomerApi.Domain.Common;

namespace MerfitCustomerApi.Domain.Entities;

/// <summary>
/// Workout varligini temsil eder.
/// </summary>
public class Workout : BaseEntity
{
    /// <summary>
    /// Antrenmanin basligi.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Antrenmanin URL dostu kisa adi.
    /// </summary>
    public string Slug { get; set; } = string.Empty;

    /// <summary>
    /// Antrenman icin kisa tanitim cumlesi.
    /// </summary>
    public string? Tagline { get; set; }

    /// <summary>
    /// Antrenmanin detayli aciklamasi.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Antrenmanin tahmini suresi (dakika).
    /// </summary>
    public int DurationMin { get; set; }

    /// <summary>
    /// Antrenmanin zorluk seviyesi.
    /// </summary>
    public DifficultyLevel Difficulty { get; set; }

    /// <summary>
    /// Antrenmanin bagli oldugu kategorinin kimligi.
    /// </summary>
    public long CategoryId { get; set; }

    /// <summary>
    /// Antrenmanin hedefledigi ana kas grubunun kimligi.
    /// </summary>
    public long? MuscleGroupId { get; set; }

    /// <summary>
    /// Antrenman gorselinin adresi.
    /// </summary>
    public string? ImageUrl { get; set; }

    /// <summary>
    /// Antrenmanin one cikarilan icerik olup olmadigi.
    /// </summary>
    public bool IsFeatured { get; set; }

    /// <summary>
    /// Antrenmanin yalnizca Plus uyeler icin olup olmadigi.
    /// </summary>
    public bool IsPremium { get; set; }

    /// <summary>
    /// Antrenmanin yapay zeka tarafindan uretilip uretilmedigi.
    /// </summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>
    /// Antrenmanin aktif/yayinda olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }
}
