// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Infrastructure.Persistence.Repositories namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitCustomerApi.Domain.Interfaces;
using MerfitCustomerApi.Domain.Interfaces.Repositories;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace MerfitCustomerApi.Infrastructure.Persistence.Repositories;

/// <summary>
/// IGenericRepository sozlesmesinin Entity Framework Core uzerinden calisan varsayilan implementasyonu.
/// </summary>
/// <typeparam name="TEntity">Repository'nin islem yapacagi entity turu.</typeparam>
public class GenericRepository<TEntity> : IGenericRepository<TEntity> where TEntity : class
{
    /// <summary>
    /// Repository'nin uzerinde calistigi veritabani baglami.
    /// </summary>
    protected readonly AppDbContext DbContext;

    /// <summary>
    /// Ilgili entity turune ait DbSet; sorgu ve komutlarin baslangic noktasidir.
    /// </summary>
    protected readonly DbSet<TEntity> DbSet;

    /// <summary>
    /// GenericRepository sinifinin yeni bir ornegini, disaridan saglanan DbContext ile olusturur.
    /// </summary>
    /// <param name="dbContext">Kullanilacak Entity Framework Core veritabani baglami.</param>
    public GenericRepository(AppDbContext dbContext)
    {
        DbContext = dbContext;
        DbSet = dbContext.Set<TEntity>();
    }

    /// <summary>
    /// Bu entity turune ait IQueryable'i dondurur; admin panelindeki liste uc noktalarinda
    /// dinamik filtreleme, siralama ve sayfalama database tarafinda uygulanabilsin diye kullanilir.
    /// </summary>
    /// <param name="asNoTracking">true ise (varsayilan) AsNoTracking() uygulanir.</param>
    public virtual IQueryable<TEntity> GetQueryable(bool asNoTracking = true)
    {
        return asNoTracking ? DbSet.AsNoTracking() : DbSet;
    }

    /// <summary>
    /// Verilen birincil anahtar (id) degerine sahip kaydi asenkron olarak getirir.
    /// </summary>
    /// <param name="id">Aranan kaydin birincil anahtar degeri.</param>
    /// <param name="cancellationToken">Islemi iptal etmek icin kullanilan token.</param>
    public virtual async Task<TEntity?> GetByIdAsync(long id, CancellationToken cancellationToken = default)
    {
        return await DbSet.FindAsync(new object?[] { id }, cancellationToken);
    }

    /// <summary>
    /// Bu entity turune ait tum kayitlari asenkron olarak getirir.
    /// </summary>
    /// <param name="cancellationToken">Islemi iptal etmek icin kullanilan token.</param>
    public virtual async Task<IReadOnlyList<TEntity>> GetAllAsync(CancellationToken cancellationToken = default)
    {
        return await DbSet.AsNoTracking().ToListAsync(cancellationToken);
    }

    /// <summary>
    /// Verilen kosula uyan kayitlari asenkron olarak getirir.
    /// </summary>
    /// <param name="predicate">Kayitlari filtrelemek icin kullanilan LINQ ifadesi.</param>
    /// <param name="cancellationToken">Islemi iptal etmek icin kullanilan token.</param>
    public virtual async Task<IReadOnlyList<TEntity>> FindAsync(Expression<Func<TEntity, bool>> predicate, CancellationToken cancellationToken = default)
    {
        return await DbSet.AsNoTracking().Where(predicate).ToListAsync(cancellationToken);
    }

    /// <summary>
    /// Verilen kosula uyan ilk kaydi asenkron olarak getirir; bulunamazsa null doner.
    /// </summary>
    /// <param name="predicate">Kaydi filtrelemek icin kullanilan LINQ ifadesi.</param>
    /// <param name="cancellationToken">Islemi iptal etmek icin kullanilan token.</param>
    public virtual async Task<TEntity?> FirstOrDefaultAsync(Expression<Func<TEntity, bool>> predicate, CancellationToken cancellationToken = default)
    {
        return await DbSet.FirstOrDefaultAsync(predicate, cancellationToken);
    }

    /// <summary>
    /// Verilen kosula uyan kayit olup olmadigini asenkron olarak kontrol eder.
    /// </summary>
    /// <param name="predicate">Kontrol edilecek kosul.</param>
    /// <param name="cancellationToken">Islemi iptal etmek icin kullanilan token.</param>
    public virtual async Task<bool> AnyAsync(Expression<Func<TEntity, bool>> predicate, CancellationToken cancellationToken = default)
    {
        return await DbSet.AnyAsync(predicate, cancellationToken);
    }

    /// <summary>
    /// Yeni bir kaydi izlemeye (tracking) alir; veritabanina yazmaz, bunun icin SaveChanges cagrilmalidir.
    /// </summary>
    /// <param name="entity">Eklenecek entity.</param>
    /// <param name="cancellationToken">Islemi iptal etmek icin kullanilan token.</param>
    public virtual async Task AddAsync(TEntity entity, CancellationToken cancellationToken = default)
    {
        await DbSet.AddAsync(entity, cancellationToken);
    }

    /// <summary>
    /// Birden fazla kaydi izlemeye (tracking) alir; veritabanina yazmaz, bunun icin SaveChanges cagrilmalidir.
    /// </summary>
    /// <param name="entities">Eklenecek entity koleksiyonu.</param>
    /// <param name="cancellationToken">Islemi iptal etmek icin kullanilan token.</param>
    public virtual async Task AddRangeAsync(IEnumerable<TEntity> entities, CancellationToken cancellationToken = default)
    {
        await DbSet.AddRangeAsync(entities, cancellationToken);
    }

    /// <summary>
    /// Var olan bir kaydi guncellenmek uzere isaretler.
    /// </summary>
    /// <param name="entity">Guncellenecek entity.</param>
    public virtual void Update(TEntity entity)
    {
        DbSet.Update(entity);
    }

    /// <summary>
    /// Bir kaydi silinmek uzere isaretler.
    /// </summary>
    /// <param name="entity">Silinecek entity.</param>
    public virtual void Remove(TEntity entity)
    {
        DbSet.Remove(entity);
    }

    /// <summary>
    /// Birden fazla kaydi silinmek uzere isaretler.
    /// </summary>
    /// <param name="entities">Silinecek entity koleksiyonu.</param>
    public virtual void RemoveRange(IEnumerable<TEntity> entities)
    {
        DbSet.RemoveRange(entities);
    }
}