// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// AiGenerationRequest varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class AiGenerationRequestConfiguration : IEntityTypeConfiguration<AiGenerationRequest>
{
    /// <summary>
    /// AiGenerationRequest varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<AiGenerationRequest> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("AiGenerationRequest", "ai");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Istegin turu.
        builder.Property(x => x.Type)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Yapay zekaya gonderilen istem (prompt) metni.
        builder.Property(x => x.Prompt)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Istegin guncel durumu.
        builder.Property(x => x.Status)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Istek icin kullanilan yapay zeka modeli.
        builder.Property(x => x.Model)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Iliskiler (foreign key) yapilandirmasi.
        // Istegi olusturan kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
