// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// AiGenerationResult varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class AiGenerationResultConfiguration : IEntityTypeConfiguration<AiGenerationResult>
{
    /// <summary>
    /// AiGenerationResult varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<AiGenerationResult> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("AiGenerationResult", "ai");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Uretilen sonucun JSON formatinda tutuldugu alan.
        builder.Property(x => x.ResultJson)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili uretim istegi kimligi.
        builder.HasOne<AiGenerationRequest>()
            .WithMany()
            .HasForeignKey(x => x.RequestId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
