// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// AppContent varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class AppContentConfiguration : IEntityTypeConfiguration<AppContent>
{
    /// <summary>
    /// AppContent varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<AppContent> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("AppContent", "content");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Icerigin sistemsel anahtari (orn. home.banner).
        builder.Property(x => x.Key)
            .IsRequired(true)
            .HasMaxLength(200);

        // Icerigin turu.
        builder.Property(x => x.Type)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Icerigin basligi.
        builder.Property(x => x.Title)
            .IsRequired(false)
            .HasMaxLength(200);

        // Icerigin aciklamasi.
        builder.Property(x => x.Description)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Icerik gorselinin adresi.
        builder.Property(x => x.ImageUrl)
            .IsRequired(false)
            .HasMaxLength(500);

        // Icerigin yonlendirdigi baglanti adresi.
        builder.Property(x => x.LinkUrl)
            .IsRequired(false)
            .HasMaxLength(500);
    }
}
