// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// AuditLog varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class AuditLogConfiguration : IEntityTypeConfiguration<AuditLog>
{
    /// <summary>
    /// AuditLog varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<AuditLog> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("AuditLog", "audit");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Gerceklesen islemin adi (orn. LOGIN, PASSWORD_CHANGED).
        builder.Property(x => x.Action)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Islemin ilgili oldugu varlik adi.
        builder.Property(x => x.Entity)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Islemin gerceklestigi IP adresi.
        builder.Property(x => x.IpAddress)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Islemin gerceklestigi istemci bilgisi (user agent).
        builder.Property(x => x.UserAgent)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Isleme dair ek verilerin JSON formatinda tutuldugu alan.
        builder.Property(x => x.MetadataJson)
            .IsRequired(false)
            .HasColumnType("jsonb");

        // Iliskiler (foreign key) yapilandirmasi.
        // Islemi gerceklestiren kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.SetNull);
    }
}
