// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// BodyMeasurement varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class BodyMeasurementConfiguration : IEntityTypeConfiguration<BodyMeasurement>
{
    /// <summary>
    /// BodyMeasurement varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<BodyMeasurement> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("BodyMeasurement", "profile");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Vucut agirligi (kilogram).
        builder.Property(x => x.WeightKg)
            .HasPrecision(18, 2);

        // Vucut yag orani (yuzde).
        builder.Property(x => x.BodyFatPercentage)
            .HasPrecision(18, 2);

        // Vucut kitle indeksi.
        builder.Property(x => x.BMI)
            .HasPrecision(18, 2);

        // Gogus cevresi (santimetre).
        builder.Property(x => x.ChestCm)
            .HasPrecision(18, 2);

        // Bel cevresi (santimetre).
        builder.Property(x => x.WaistCm)
            .HasPrecision(18, 2);

        // Kalca cevresi (santimetre).
        builder.Property(x => x.HipCm)
            .HasPrecision(18, 2);

        // Kol cevresi (santimetre).
        builder.Property(x => x.ArmCm)
            .HasPrecision(18, 2);

        // Uyluk cevresi (santimetre).
        builder.Property(x => x.ThighCm)
            .HasPrecision(18, 2);

        // Iliskiler (foreign key) yapilandirmasi.
        // Olcumun ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
