// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// Exercise varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class ExerciseConfiguration : IEntityTypeConfiguration<Exercise>
{
    /// <summary>
    /// Exercise varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Exercise> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Exercise", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Egzersizin adi.
        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);

        // Egzersizin URL dostu kisa adi.
        builder.Property(x => x.Slug)
            .IsRequired(true)
            .HasMaxLength(200);

        // Egzersizin genel aciklamasi.
        builder.Property(x => x.Description)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Egzersizin nasil yapilacagina dair adim adim talimatlar.
        builder.Property(x => x.Instructions)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Egzersizin zorluk seviyesi.
        builder.Property(x => x.Difficulty)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Egzersiz icin gereken ekipman turunu belirten serbest metin.
        builder.Property(x => x.EquipmentType)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Egzersiz anlatim videosunun adresi.
        builder.Property(x => x.VideoUrl)
            .IsRequired(false)
            .HasMaxLength(500);

        // Egzersiz gorselinin adresi.
        builder.Property(x => x.ImageUrl)
            .IsRequired(false)
            .HasMaxLength(500);

        // Egzersizin dakika basina yaktigi tahmini kalori.
        builder.Property(x => x.CaloriesPerMinute)
            .HasPrecision(18, 2);

        // Iliskiler (foreign key) yapilandirmasi.
        // Egzersizin hedefledigi ana kas grubunun kimligi.
        builder.HasOne<MuscleGroup>()
            .WithMany()
            .HasForeignKey(x => x.PrimaryMuscleGroupId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
