// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// ExternalLogin varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class ExternalLoginConfiguration : IEntityTypeConfiguration<ExternalLogin>
{
    /// <summary>
    /// ExternalLogin varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<ExternalLogin> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("ExternalLogin", "authentication");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Harici giris saglayicisi (orn. Apple, Google).
        builder.Property(x => x.Provider)
            .IsRequired(true)
            .HasMaxLength(200);

        // Saglayici tarafindaki kullanici kimligi.
        builder.Property(x => x.ProviderUserId)
            .IsRequired(true)
            .HasMaxLength(200);

        // Saglayicidan alinan e-posta adresi.
        builder.Property(x => x.Email)
            .IsRequired(false)
            .HasMaxLength(500);

        // Iliskiler (foreign key) yapilandirmasi.
        // Girisin ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
