// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// FAQCategory varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class FAQCategoryConfiguration : IEntityTypeConfiguration<FAQCategory>
{
    /// <summary>
    /// FAQCategory varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<FAQCategory> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("FAQCategory", "content");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Kategorinin adi.
        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);
    }
}
