// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// FAQ varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class FAQConfiguration : IEntityTypeConfiguration<FAQ>
{
    /// <summary>
    /// FAQ varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<FAQ> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("FAQ", "content");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Sorulan soru metni.
        builder.Property(x => x.Question)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Soruya verilen cevap metni.
        builder.Property(x => x.Answer)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili SSS kategorisinin kimligi.
        builder.HasOne<FAQCategory>()
            .WithMany()
            .HasForeignKey(x => x.CategoryId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
