// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// Food varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class FoodConfiguration : IEntityTypeConfiguration<Food>
{
    /// <summary>
    /// Food varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Food> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Food", "nutrition");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Besinin adi.
        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);

        // Besinin barkod numarasi.
        builder.Property(x => x.Barcode)
            .IsRequired(false)
            .HasMaxLength(300);

        // Besinin markasi.
        builder.Property(x => x.Brand)
            .IsRequired(false)
            .HasMaxLength(200);

        // Referans porsiyon miktari.
        builder.Property(x => x.ServingSize)
            .HasPrecision(18, 2);

        // Porsiyon birimi (orn. gram, ml, adet).
        builder.Property(x => x.ServingUnit)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Porsiyon basina kalori miktari.
        builder.Property(x => x.Calories)
            .HasPrecision(18, 2);

        // Porsiyon basina protein miktari (gram).
        builder.Property(x => x.Protein)
            .HasPrecision(18, 2);

        // Porsiyon basina karbonhidrat miktari (gram).
        builder.Property(x => x.Carbs)
            .HasPrecision(18, 2);

        // Porsiyon basina yag miktari (gram).
        builder.Property(x => x.Fat)
            .HasPrecision(18, 2);

        // Porsiyon basina lif miktari (gram).
        builder.Property(x => x.Fiber)
            .HasPrecision(18, 2);

        // Porsiyon basina seker miktari (gram).
        builder.Property(x => x.Sugar)
            .HasPrecision(18, 2);

        // Porsiyon basina sodyum miktari (miligram).
        builder.Property(x => x.Sodium)
            .HasPrecision(18, 2);

        // Besin gorselinin adresi.
        builder.Property(x => x.ImageUrl)
            .IsRequired(false)
            .HasMaxLength(500);
    }
}
