// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// GoalHistory varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class GoalHistoryConfiguration : IEntityTypeConfiguration<GoalHistory>
{
    /// <summary>
    /// GoalHistory varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<GoalHistory> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("GoalHistory", "profile");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Degisiklikten onceki hedef.
        builder.Property(x => x.OldGoal)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Degisiklikten sonraki hedef.
        builder.Property(x => x.NewGoal)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Hedef degisikliginin nedeni.
        builder.Property(x => x.Reason)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Iliskiler (foreign key) yapilandirmasi.
        // Hedefi degistiren kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
