// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// Language varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class LanguageConfiguration : IEntityTypeConfiguration<Language>
{
    /// <summary>
    /// Language varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Language> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Language", "content");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Dilin ISO koduna (orn. tr, en) karsilik gelen degeri.
        builder.Property(x => x.Code)
            .IsRequired(true)
            .HasMaxLength(200);

        // Dilin adi.
        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);
    }
}
