// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// LeaderboardEntry varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class LeaderboardEntryConfiguration : IEntityTypeConfiguration<LeaderboardEntry>
{
    /// <summary>
    /// LeaderboardEntry varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<LeaderboardEntry> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("LeaderboardEntry", "gamification");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Kullanicinin bu donemde topladigi puan.
        builder.Property(x => x.Points)
            .HasPrecision(18, 2);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili donemin kimligi.
        builder.HasOne<LeaderboardPeriod>()
            .WithMany()
            .HasForeignKey(x => x.LeaderboardPeriodId)
            .OnDelete(DeleteBehavior.Restrict);

        // Siralamadaki kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
