// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// LeaderboardReward varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class LeaderboardRewardConfiguration : IEntityTypeConfiguration<LeaderboardReward>
{
    /// <summary>
    /// LeaderboardReward varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<LeaderboardReward> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("LeaderboardReward", "gamification");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili donemin kimligi.
        builder.HasOne<LeaderboardPeriod>()
            .WithMany()
            .HasForeignKey(x => x.LeaderboardPeriodId)
            .OnDelete(DeleteBehavior.Restrict);

        // Verilecek odulun kimligi.
        builder.HasOne<Reward>()
            .WithMany()
            .HasForeignKey(x => x.RewardId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
