// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// LeaderboardPeriod varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class LeaderboardPeriodConfiguration : IEntityTypeConfiguration<LeaderboardPeriod>
{
    /// <summary>
    /// LeaderboardPeriod varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<LeaderboardPeriod> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("LeaderboardPeriod", "gamification");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Donemin turu (haftalik, aylik, tum zamanlar).
        builder.Property(x => x.Type)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);
    }
}
