// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// Meal varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class MealConfiguration : IEntityTypeConfiguration<Meal>
{
    /// <summary>
    /// Meal varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Meal> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Meal", "nutrition");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Ogunun turu (kahvalti, ogle, aksam, ara ogun).
        builder.Property(x => x.MealType)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Oguna ait notlar.
        builder.Property(x => x.Notes)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Iliskiler (foreign key) yapilandirmasi.
        // Ogunu kaydeden kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
