// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// MealItem varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class MealItemConfiguration : IEntityTypeConfiguration<MealItem>
{
    /// <summary>
    /// MealItem varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<MealItem> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("MealItem", "nutrition");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Tuketilen miktar.
        builder.Property(x => x.Quantity)
            .HasPrecision(18, 2);

        // Kayit anindaki porsiyon buyuklugu (anlik goruntu).
        builder.Property(x => x.ServingSize)
            .HasPrecision(18, 2);

        // Kayit anindaki kalori miktari (anlik goruntu).
        builder.Property(x => x.Calories)
            .HasPrecision(18, 2);

        // Kayit anindaki protein miktari (anlik goruntu).
        builder.Property(x => x.Protein)
            .HasPrecision(18, 2);

        // Kayit anindaki karbonhidrat miktari (anlik goruntu).
        builder.Property(x => x.Carbs)
            .HasPrecision(18, 2);

        // Kayit anindaki yag miktari (anlik goruntu).
        builder.Property(x => x.Fat)
            .HasPrecision(18, 2);

        // Kayit anindaki lif miktari (anlik goruntu).
        builder.Property(x => x.Fiber)
            .HasPrecision(18, 2);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili ogunun kimligi.
        builder.HasOne<Meal>()
            .WithMany()
            .HasForeignKey(x => x.MealId)
            .OnDelete(DeleteBehavior.Restrict);

        // Iliskili besinin kimligi.
        builder.HasOne<Food>()
            .WithMany()
            .HasForeignKey(x => x.FoodId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
