// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// MerfitScoreBreakdown varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class MerfitScoreBreakdownConfiguration : IEntityTypeConfiguration<MerfitScoreBreakdown>
{
    /// <summary>
    /// MerfitScoreBreakdown varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<MerfitScoreBreakdown> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("MerfitScoreBreakdown", "gamification");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Skor kaleminin kategorisi (orn. Consistency, Workouts).
        builder.Property(x => x.Category)
            .IsRequired(true)
            .HasMaxLength(300);

        // Bu kategoriden kazanilan puan.
        builder.Property(x => x.Points)
            .HasPrecision(18, 2);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili Merfit skorunun kimligi.
        builder.HasOne<MerfitScore>()
            .WithMany()
            .HasForeignKey(x => x.MerfitScoreId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
