// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// MerfitScore varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class MerfitScoreConfiguration : IEntityTypeConfiguration<MerfitScore>
{
    /// <summary>
    /// MerfitScore varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<MerfitScore> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("MerfitScore", "gamification");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Hesaplanan toplam skor degeri.
        builder.Property(x => x.Score)
            .HasPrecision(18, 2);

        // Skorun hesaplandigi donemi ifade eden deger.
        builder.Property(x => x.Period)
            .IsRequired(true)
            .HasMaxLength(300);

        // Iliskiler (foreign key) yapilandirmasi.
        // Skorun ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
