// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// MuscleGroup varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class MuscleGroupConfiguration : IEntityTypeConfiguration<MuscleGroup>
{
    /// <summary>
    /// MuscleGroup varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<MuscleGroup> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("MuscleGroup", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Kas grubunun adi (orn. Gogus, Sirt).
        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);

        // Kas grubunun URL dostu kisa adi.
        builder.Property(x => x.Slug)
            .IsRequired(true)
            .HasMaxLength(200);
    }
}
