// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// Notification varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class NotificationConfiguration : IEntityTypeConfiguration<Notification>
{
    /// <summary>
    /// Notification varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Notification> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Notification", "notification");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Bildirimin turu.
        builder.Property(x => x.Type)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Bildirimin basligi.
        builder.Property(x => x.Title)
            .IsRequired(true)
            .HasMaxLength(200);

        // Bildirimin icerik metni.
        builder.Property(x => x.Body)
            .IsRequired(true)
            .HasMaxLength(300);

        // Bildirime ait ek verilerin JSON formatinda tutuldugu alan.
        builder.Property(x => x.DataJson)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Bildirimde gosterilen gorselin adresi.
        builder.Property(x => x.ImageUrl)
            .IsRequired(false)
            .HasMaxLength(500);

        // Iliskiler (foreign key) yapilandirmasi.
        // Bildirimin gonderildigi kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
