// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>NutritionPlan varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.</summary>
public class NutritionPlanConfiguration : IEntityTypeConfiguration<NutritionPlan>
{
    public void Configure(EntityTypeBuilder<NutritionPlan> builder)
    {
        builder.ToTable("NutritionPlan", "nutrition");
        builder.HasKey(x => x.Id);

        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);

        builder.Property(x => x.Description)
            .IsRequired(false)
            .HasMaxLength(1000);

        // Kullanici basina ayni anda birden fazla aktif plan olusmasini onlemek amacli sorgularda
        // kullanilacak birlesik index (uygulama katmaninda transaction ile de garanti edilir).
        builder.HasIndex(x => new { x.UserId, x.IsActive });

        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}

/// <summary>NutritionPlanDay varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.</summary>
public class NutritionPlanDayConfiguration : IEntityTypeConfiguration<NutritionPlanDay>
{
    public void Configure(EntityTypeBuilder<NutritionPlanDay> builder)
    {
        builder.ToTable("NutritionPlanDay", "nutrition");
        builder.HasKey(x => x.Id);

        builder.HasIndex(x => new { x.NutritionPlanId, x.DayOfWeek });

        builder.HasOne<NutritionPlan>()
            .WithMany()
            .HasForeignKey(x => x.NutritionPlanId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}

/// <summary>NutritionPlanMeal varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.</summary>
public class NutritionPlanMealConfiguration : IEntityTypeConfiguration<NutritionPlanMeal>
{
    public void Configure(EntityTypeBuilder<NutritionPlanMeal> builder)
    {
        builder.ToTable("NutritionPlanMeal", "nutrition");
        builder.HasKey(x => x.Id);

        builder.Property(x => x.MealType)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);

        builder.Property(x => x.Notes)
            .IsRequired(false)
            .HasMaxLength(1000);

        builder.HasIndex(x => x.NutritionPlanDayId);

        builder.HasOne<NutritionPlanDay>()
            .WithMany()
            .HasForeignKey(x => x.NutritionPlanDayId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}

/// <summary>NutritionPlanMealItem varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.</summary>
public class NutritionPlanMealItemConfiguration : IEntityTypeConfiguration<NutritionPlanMealItem>
{
    public void Configure(EntityTypeBuilder<NutritionPlanMealItem> builder)
    {
        builder.ToTable("NutritionPlanMealItem", "nutrition");
        builder.HasKey(x => x.Id);

        builder.Property(x => x.ServingUnit)
            .IsRequired(true)
            .HasMaxLength(20);

        builder.Property(x => x.Quantity).HasPrecision(18, 2);
        builder.Property(x => x.Calories).HasPrecision(18, 2);
        builder.Property(x => x.Protein).HasPrecision(18, 2);
        builder.Property(x => x.Carbs).HasPrecision(18, 2);
        builder.Property(x => x.Fat).HasPrecision(18, 2);

        builder.HasIndex(x => x.NutritionPlanMealId);

        builder.HasOne<NutritionPlanMeal>()
            .WithMany()
            .HasForeignKey(x => x.NutritionPlanMealId)
            .OnDelete(DeleteBehavior.Cascade);

        // Food silinemez/pasiflestirilir varsayimiyla Restrict; snapshot alanlar zaten
        // Food'daki guncel degerden bagimsiz calisir, FoodId yalnizca referans/gosterim icindir.
        builder.HasOne<Food>()
            .WithMany()
            .HasForeignKey(x => x.FoodId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
