// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// NutritionGoal varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class NutritionGoalConfiguration : IEntityTypeConfiguration<NutritionGoal>
{
    /// <summary>
    /// NutritionGoal varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<NutritionGoal> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("NutritionGoal", "nutrition");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Gunluk hedeflenen kalori miktari.
        builder.Property(x => x.DailyCalories)
            .HasPrecision(18, 2);

        // Gunluk hedeflenen protein miktari (gram).
        builder.Property(x => x.ProteinTarget)
            .HasPrecision(18, 2);

        // Gunluk hedeflenen karbonhidrat miktari (gram).
        builder.Property(x => x.CarbsTarget)
            .HasPrecision(18, 2);

        // Gunluk hedeflenen yag miktari (gram).
        builder.Property(x => x.FatTarget)
            .HasPrecision(18, 2);

        // Gunluk hedeflenen su miktari (mililitre).
        builder.Property(x => x.WaterTargetMl)
            .HasPrecision(18, 2);

        // Iliskiler (foreign key) yapilandirmasi.
        // Hedefin ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
