// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// PersonalRecord varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class PersonalRecordConfiguration : IEntityTypeConfiguration<PersonalRecord>
{
    /// <summary>
    /// PersonalRecord varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<PersonalRecord> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("PersonalRecord", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Rekor sirasinda kaldirilan agirlik (kilogram).
        builder.Property(x => x.WeightKg)
            .HasPrecision(18, 2);

        // Hesaplanan tahmini bir tekrar maksimumu (1RM).
        builder.Property(x => x.EstimatedOneRepMax)
            .HasPrecision(18, 2);

        // Iliskiler (foreign key) yapilandirmasi.
        // Rekoru kiran kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        // Rekorun ait oldugu egzersizin kimligi.
        builder.HasOne<Exercise>()
            .WithMany()
            .HasForeignKey(x => x.ExerciseId)
            .OnDelete(DeleteBehavior.Restrict);

        // Rekorun kirildigi antrenman oturumunun kimligi.
        builder.HasOne<WorkoutSession>()
            .WithMany()
            .HasForeignKey(x => x.WorkoutSessionId)
            .OnDelete(DeleteBehavior.SetNull);
    }
}
