// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// PersonalizationJob varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class PersonalizationJobConfiguration : IEntityTypeConfiguration<PersonalizationJob>
{
    /// <summary>
    /// PersonalizationJob varligi icin tablo adi, birincil anahtar, alan kisitlari, index ve
    /// iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<PersonalizationJob> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("PersonalizationJob", "profile");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Isin guncel durumu.
        builder.Property(x => x.Status)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Isin kac kez denendigi.
        builder.Property(x => x.AttemptCount)
            .IsRequired(true)
            .HasDefaultValue(0);

        // Is basarisiz oldugunda son hata mesaji.
        builder.Property(x => x.ErrorMessage)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Kullanici basina kuyruktaki/islenen isleri hizli sorgulayabilmek icin index.
        builder.HasIndex(x => x.UserId);

        // Ayni anda ayni kullanici icin birden fazla bekleyen/islenen (henuz sonuclanmamis)
        // is olusmasini engellemek amacli sorgularda kullanilacak birlesik index.
        builder.HasIndex(x => new { x.UserId, x.Status });

        // Iliskiler (foreign key) yapilandirmasi.
        // Isin ait oldugu kullanicinin kimligi. Kullanici silinirse ilgili is kayitlari da silinir;
        // bu tablo yalnizca islem takibi tuttugu ve referans butunlugu bozmadigi icin Cascade uygundur.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
