// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// Reward varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class RewardConfiguration : IEntityTypeConfiguration<Reward>
{
    /// <summary>
    /// Reward varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Reward> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Reward", "gamification");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Odulun basligi.
        builder.Property(x => x.Title)
            .IsRequired(true)
            .HasMaxLength(200);

        // Odulun aciklamasi.
        builder.Property(x => x.Description)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Odul gorselinin adresi.
        builder.Property(x => x.ImageUrl)
            .IsRequired(false)
            .HasMaxLength(500);

        // Odulun turu (orn. watch, premium, bag).
        builder.Property(x => x.RewardType)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Odule ait deger/detay bilgisi.
        builder.Property(x => x.Value)
            .IsRequired(false)
            .HasMaxLength(2000);
    }
}
