// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// SubscriptionPlanFeature varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class SubscriptionPlanFeatureConfiguration : IEntityTypeConfiguration<SubscriptionPlanFeature>
{
    /// <summary>
    /// SubscriptionPlanFeature varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<SubscriptionPlanFeature> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("SubscriptionPlanFeature", "subscription");

        // Birlesik (composite) birincil anahtari tanimlar.
        builder.HasKey(x => new { x.SubscriptionProductId, x.FeatureId });

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili abonelik urununun kimligi.
        builder.HasOne<SubscriptionProduct>()
            .WithMany()
            .HasForeignKey(x => x.SubscriptionProductId)
            .OnDelete(DeleteBehavior.Restrict);

        // Iliskili ozelligin kimligi.
        builder.HasOne<Feature>()
            .WithMany()
            .HasForeignKey(x => x.FeatureId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
