// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// SubscriptionTransaction varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class SubscriptionTransactionConfiguration : IEntityTypeConfiguration<SubscriptionTransaction>
{
    /// <summary>
    /// SubscriptionTransaction varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<SubscriptionTransaction> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("SubscriptionTransaction", "subscription");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Islemin gerceklestigi magaza saglayicisi.
        builder.Property(x => x.Provider)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Magaza tarafindaki benzersiz islem kimligi.
        builder.Property(x => x.TransactionId)
            .IsRequired(true)
            .HasMaxLength(300);

        // Yenilemelerde referans olan ilk islem kimligi.
        builder.Property(x => x.OriginalTransactionId)
            .IsRequired(false)
            .HasMaxLength(300);

        // Magazadaki urun kimligi.
        builder.Property(x => x.ProductId)
            .IsRequired(true)
            .HasMaxLength(200);

        // Islem tutari.
        builder.Property(x => x.Amount)
            .HasPrecision(18, 2);

        // Islemin para birimi.
        builder.Property(x => x.Currency)
            .IsRequired(true)
            .HasMaxLength(200);

        // Magazadan alinan ham makbuz verisi.
        builder.Property(x => x.RawReceipt)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili aboneligin kimligi.
        builder.HasOne<Subscription>()
            .WithMany()
            .HasForeignKey(x => x.SubscriptionId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
