// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// SubscriptionProduct varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class SubscriptionProductConfiguration : IEntityTypeConfiguration<SubscriptionProduct>
{
    /// <summary>
    /// SubscriptionProduct varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<SubscriptionProduct> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("SubscriptionProduct", "subscription");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Urunun sistemsel kodu (orn. MERFIT_PLUS_MONTHLY).
        builder.Property(x => x.Code)
            .IsRequired(true)
            .HasMaxLength(200);

        // Urunun adi.
        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);

        // App Store urun kimligi.
        builder.Property(x => x.StoreProductIdIos)
            .IsRequired(false)
            .HasMaxLength(300);

        // Google Play urun kimligi.
        builder.Property(x => x.StoreProductIdAndroid)
            .IsRequired(false)
            .HasMaxLength(300);

        // Urunun faturalama periyodu.
        builder.Property(x => x.BillingPeriod)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Urunun fiyati.
        builder.Property(x => x.Price)
            .HasPrecision(18, 2);

        // Fiyatin para birimi.
        builder.Property(x => x.Currency)
            .IsRequired(true)
            .HasMaxLength(200);
    }
}
