// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// Subscription varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class SubscriptionConfiguration : IEntityTypeConfiguration<Subscription>
{
    /// <summary>
    /// Subscription varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Subscription> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Subscription", "subscription");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Odemenin gerceklestigi magaza saglayicisi.
        builder.Property(x => x.Provider)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Magaza tarafindaki islem kimligi.
        builder.Property(x => x.ExternalTransactionId)
            .IsRequired(false)
            .HasMaxLength(300);

        // Abonelik durumu.
        builder.Property(x => x.Status)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Iliskiler (foreign key) yapilandirmasi.
        // Abonelik sahibi kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        // Satin alinan abonelik urununun kimligi.
        builder.HasOne<SubscriptionProduct>()
            .WithMany()
            .HasForeignKey(x => x.SubscriptionProductId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
