// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// Translation varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class TranslationConfiguration : IEntityTypeConfiguration<Translation>
{
    /// <summary>
    /// Translation varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Translation> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Translation", "content");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Ceviri metnine karsilik gelen anahtar (orn. workout.start).
        builder.Property(x => x.ResourceKey)
            .IsRequired(true)
            .HasMaxLength(200);

        // Anahtara karsilik gelen cevrilmis metin.
        builder.Property(x => x.Value)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili dilin kimligi.
        builder.HasOne<Language>()
            .WithMany()
            .HasForeignKey(x => x.LanguageId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
