// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// UserRefreshToken varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class UserRefreshTokenConfiguration : IEntityTypeConfiguration<UserRefreshToken>
{
    /// <summary>
    /// UserRefreshToken varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<UserRefreshToken> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("UserRefreshToken", "authentication");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Yenileme jetonunun degeri.
        builder.Property(x => x.Token)
            .IsRequired(true)
            .HasMaxLength(500);

        // Jetonun olusturuldugu IP adresi.
        builder.Property(x => x.CreatedByIp)
            .IsRequired(false)
            .HasMaxLength(300);

        // Jetonun iptal edildigi IP adresi.
        builder.Property(x => x.RevokedByIp)
            .IsRequired(false)
            .HasMaxLength(300);

        // Bu jetonun yerine gecen yeni jeton degeri.
        builder.Property(x => x.ReplacementToken)
            .IsRequired(false)
            .HasMaxLength(500);

        // Iliskiler (foreign key) yapilandirmasi.
        // Jetonun ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
