// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// UserStreak varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class UserStreakConfiguration : IEntityTypeConfiguration<UserStreak>
{
    /// <summary>
    /// UserStreak varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<UserStreak> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("UserStreak", "profile");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Iliskiler (foreign key) yapilandirmasi.
        // Serinin ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
