// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// UserDevice varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class UserDeviceConfiguration : IEntityTypeConfiguration<UserDevice>
{
    /// <summary>
    /// UserDevice varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<UserDevice> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("UserDevice", "authentication");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Push bildirimleri icin cihaz jetonu.
        builder.Property(x => x.DeviceToken)
            .IsRequired(true)
            .HasMaxLength(500);

        // Cihazin isletim sistemi platformu.
        builder.Property(x => x.Platform)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Cihazin adi.
        builder.Property(x => x.DeviceName)
            .IsRequired(false)
            .HasMaxLength(200);

        // Cihazda yuklu uygulama surumu.
        builder.Property(x => x.AppVersion)
            .IsRequired(false)
            .HasMaxLength(300);

        // Cihazin isletim sistemi surumu.
        builder.Property(x => x.OsVersion)
            .IsRequired(false)
            .HasMaxLength(300);

        // Iliskiler (foreign key) yapilandirmasi.
        // Cihazin ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
