// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// UserProfile varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class UserProfileConfiguration : IEntityTypeConfiguration<UserProfile>
{
    /// <summary>
    /// UserProfile varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<UserProfile> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("UserProfile", "profile");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Kullanicinin adi.
        builder.Property(x => x.FirstName)
            .IsRequired(true)
            .HasMaxLength(200);

        // Kullanicinin soyadi.
        builder.Property(x => x.LastName)
            .IsRequired(true)
            .HasMaxLength(200);

        // Profilde gosterilen kullanici adi. BILINCLI URUN KARARI: bu kolon uzerinde herhangi bir
        // veritabani index'i/unique constraint'i TANIMLANMAZ. Benzersizlik yalnizca uygulama
        // katmaninda (bkz. AuthService.RegisterAsync ve ProfileService.ApplyIdentityChangesAsync
        // icindeki AnyAsync kontrolleri) saglanir. Bunun es zamanli (concurrent) istekler icin
        // teorik bir race condition penceresi biraktigi bilinerek kabul edilmistir.
        builder.Property(x => x.Username)
            .IsRequired(true)
            .HasMaxLength(300);

        // Kullanicinin cinsiyeti.
        builder.Property(x => x.Gender)
            .HasConversion<string>()
            .IsRequired(false)
            .HasMaxLength(50);

        // Kullanicinin boyu (santimetre).
        builder.Property(x => x.HeightCm)
            .HasPrecision(18, 2);

        // Kullanicinin guncel kilosu (kilogram).
        builder.Property(x => x.WeightKg)
            .HasPrecision(18, 2);

        // Kullanicinin hedefledigi kilo (kilogram).
        builder.Property(x => x.TargetWeightKg)
            .HasPrecision(18, 2);

        // Profil fotografinin adresi.
        builder.Property(x => x.ProfileImageUrl)
            .IsRequired(false)
            .HasMaxLength(500);

        // Kullanicinin genel fitness hedefi.
        builder.Property(x => x.Goal)
            .HasConversion<string>()
            .IsRequired(false)
            .HasMaxLength(50);

        // Kullanicinin antrenman deneyim seviyesi.
        builder.Property(x => x.ExperienceLevel)
            .HasConversion<string>()
            .IsRequired(false)
            .HasMaxLength(50);

        // Kullanicinin gunluk aktivite seviyesi.
        builder.Property(x => x.ActivityLevel)
            .HasConversion<string>()
            .IsRequired(false)
            .HasMaxLength(50);

        // Kullanicinin antrenman yaptigi ortam.
        builder.Property(x => x.TrainingLocation)
            .HasConversion<string>()
            .IsRequired(false)
            .HasMaxLength(50);

        // Kullanicinin tercih ettigi olcum birimi sistemi.
        builder.Property(x => x.UnitSystem)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Iliskiler (foreign key) yapilandirmasi.
        // Profilin ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
