// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// UserAchievement varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class UserAchievementConfiguration : IEntityTypeConfiguration<UserAchievement>
{
    /// <summary>
    /// UserAchievement varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<UserAchievement> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("UserAchievement", "gamification");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Iliskiler (foreign key) yapilandirmasi.
        // Basariyi kazanan kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        // Kazanilan basarinin kimligi.
        builder.HasOne<Achievement>()
            .WithMany()
            .HasForeignKey(x => x.AchievementId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
