// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// UserGoal varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class UserGoalConfiguration : IEntityTypeConfiguration<UserGoal>
{
    /// <summary>
    /// UserGoal varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<UserGoal> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("UserGoal", "profile");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Hedefin turu.
        builder.Property(x => x.GoalType)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Hedef baslangicindaki kilo (kilogram).
        builder.Property(x => x.StartingWeightKg)
            .HasPrecision(18, 2);

        // Hedef surecindeki guncel kilo (kilogram).
        builder.Property(x => x.CurrentWeightKg)
            .HasPrecision(18, 2);

        // Hedeflenen kilo (kilogram).
        builder.Property(x => x.TargetWeightKg)
            .HasPrecision(18, 2);

        // Hedefe ulasma yuzdesi.
        builder.Property(x => x.ProgressPercent)
            .HasPrecision(18, 2);

        // Iliskiler (foreign key) yapilandirmasi.
        // Hedefin ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
