// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// UserPreference varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class UserPreferenceConfiguration : IEntityTypeConfiguration<UserPreference>
{
    /// <summary>
    /// UserPreference varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<UserPreference> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("UserPreference", "profile");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Kullanicinin tercih ettigi uygulama dili.
        builder.Property(x => x.Language)
            .IsRequired(true)
            .HasMaxLength(200);

        // Kullanicinin tercih ettigi gorunum temasi.
        builder.Property(x => x.Theme)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Kullanicinin tercih ettigi olcum birimi sistemi.
        builder.Property(x => x.UnitSystem)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Iliskiler (foreign key) yapilandirmasi.
        // Tercihin ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
