// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// UserConsent varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class UserConsentConfiguration : IEntityTypeConfiguration<UserConsent>
{
    /// <summary>
    /// UserConsent varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<UserConsent> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("UserConsent", "profile");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Onayin verildigi IP adresi.
        builder.Property(x => x.IpAddress)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Onaylanan belge surumu.
        builder.Property(x => x.Version)
            .IsRequired(true)
            .HasMaxLength(300);

        // Iliskiler (foreign key) yapilandirmasi.
        // Onayi veren kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        // Onaylanan yasal belgenin kimligi.
        builder.HasOne<LegalDocument>()
            .WithMany()
            .HasForeignKey(x => x.DocumentId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
