// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// WaterLog varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WaterLogConfiguration : IEntityTypeConfiguration<WaterLog>
{
    /// <summary>
    /// WaterLog varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<WaterLog> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("WaterLog", "nutrition");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Tuketilen su miktari (mililitre).
        builder.Property(x => x.AmountMl)
            .HasPrecision(18, 2);

        // Iliskiler (foreign key) yapilandirmasi.
        // Kaydi olusturan kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
