// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// WorkoutPlanDay varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WorkoutPlanDayConfiguration : IEntityTypeConfiguration<WorkoutPlanDay>
{
    /// <summary>
    /// WorkoutPlanDay varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<WorkoutPlanDay> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("WorkoutPlanDay", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili antrenman planinin kimligi.
        builder.HasOne<WorkoutPlan>()
            .WithMany()
            .HasForeignKey(x => x.WorkoutPlanId)
            .OnDelete(DeleteBehavior.Restrict);

        // O gun icin planlanan antrenmanin kimligi.
        builder.HasOne<Workout>()
            .WithMany()
            .HasForeignKey(x => x.WorkoutId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
