// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// WorkoutExercise varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WorkoutExerciseConfiguration : IEntityTypeConfiguration<WorkoutExercise>
{
    /// <summary>
    /// WorkoutExercise varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<WorkoutExercise> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("WorkoutExercise", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Egzersize ozel notlar.
        builder.Property(x => x.Notes)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili antrenmanin kimligi.
        builder.HasOne<Workout>()
            .WithMany()
            .HasForeignKey(x => x.WorkoutId)
            .OnDelete(DeleteBehavior.Restrict);

        // Iliskili egzersizin kimligi.
        builder.HasOne<Exercise>()
            .WithMany()
            .HasForeignKey(x => x.ExerciseId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
