// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// WorkoutSetLog varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WorkoutSetLogConfiguration : IEntityTypeConfiguration<WorkoutSetLog>
{
    /// <summary>
    /// WorkoutSetLog varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<WorkoutSetLog> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("WorkoutSetLog", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Sette kullanilan agirlik (kilogram).
        builder.Property(x => x.WeightKg)
            .HasPrecision(18, 2);

        // Setin algilanan zorluk derecesi (RPE).
        builder.Property(x => x.Rpe)
            .HasPrecision(18, 2);

        // Sete ait notlar.
        builder.Property(x => x.Notes)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili oturum-egzersiz kaydinin kimligi.
        builder.HasOne<WorkoutSessionExercise>()
            .WithMany()
            .HasForeignKey(x => x.WorkoutSessionExerciseId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
