// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// Workout varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WorkoutConfiguration : IEntityTypeConfiguration<Workout>
{
    /// <summary>
    /// Workout varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Workout> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Workout", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Antrenmanin basligi.
        builder.Property(x => x.Title)
            .IsRequired(true)
            .HasMaxLength(200);

        // Antrenmanin URL dostu kisa adi.
        builder.Property(x => x.Slug)
            .IsRequired(true)
            .HasMaxLength(200);

        // Antrenman icin kisa tanitim cumlesi.
        builder.Property(x => x.Tagline)
            .IsRequired(false)
            .HasMaxLength(300);

        // Antrenmanin detayli aciklamasi.
        builder.Property(x => x.Description)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Antrenmanin zorluk seviyesi.
        builder.Property(x => x.Difficulty)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Antrenman gorselinin adresi.
        builder.Property(x => x.ImageUrl)
            .IsRequired(false)
            .HasMaxLength(500);

        // Iliskiler (foreign key) yapilandirmasi.
        // Antrenmanin bagli oldugu kategorinin kimligi.
        builder.HasOne<WorkoutCategory>()
            .WithMany()
            .HasForeignKey(x => x.CategoryId)
            .OnDelete(DeleteBehavior.Restrict);

        // Antrenmanin hedefledigi ana kas grubunun kimligi.
        builder.HasOne<MuscleGroup>()
            .WithMany()
            .HasForeignKey(x => x.MuscleGroupId)
            .OnDelete(DeleteBehavior.SetNull);
    }
}
