// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;
using MerfitCustomerApi.Domain.Entities.Enums;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// WorkoutSession varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WorkoutSessionConfiguration : IEntityTypeConfiguration<WorkoutSession>
{
    /// <summary>
    /// WorkoutSession varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<WorkoutSession> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("WorkoutSession", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Oturumun guncel durumu.
        builder.Property(x => x.Status)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Oturumda yakilan tahmini kalori.
        builder.Property(x => x.CaloriesBurned)
            .HasPrecision(18, 2);

        // Oturuma ait notlar.
        builder.Property(x => x.Notes)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Iliskiler (foreign key) yapilandirmasi.
        // Oturumu gerceklestiren kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        // Gerceklestirilen antrenmanin kimligi.
        builder.HasOne<Workout>()
            .WithMany()
            .HasForeignKey(x => x.WorkoutId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
