// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// WorkoutCategory varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WorkoutCategoryConfiguration : IEntityTypeConfiguration<WorkoutCategory>
{
    /// <summary>
    /// WorkoutCategory varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<WorkoutCategory> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("WorkoutCategory", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Kategorinin adi (orn. Strength, Cardio).
        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);

        // Kategorinin URL dostu kisa adi.
        builder.Property(x => x.Slug)
            .IsRequired(true)
            .HasMaxLength(200);

        // Kategorinin aciklamasi.
        builder.Property(x => x.Description)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Kategori gorselinin adresi.
        builder.Property(x => x.ImageUrl)
            .IsRequired(false)
            .HasMaxLength(500);
    }
}
