// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// WorkoutEquipment varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WorkoutEquipmentConfiguration : IEntityTypeConfiguration<WorkoutEquipment>
{
    /// <summary>
    /// WorkoutEquipment varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<WorkoutEquipment> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("WorkoutEquipment", "workout");

        // Birlesik (composite) birincil anahtari tanimlar.
        builder.HasKey(x => new { x.WorkoutId, x.EquipmentId });

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili antrenmanin kimligi.
        builder.HasOne<Workout>()
            .WithMany()
            .HasForeignKey(x => x.WorkoutId)
            .OnDelete(DeleteBehavior.Restrict);

        // Iliskili ekipmanin kimligi.
        builder.HasOne<Equipment>()
            .WithMany()
            .HasForeignKey(x => x.EquipmentId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
