// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// WorkoutSessionExercise varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WorkoutSessionExerciseConfiguration : IEntityTypeConfiguration<WorkoutSessionExercise>
{
    /// <summary>
    /// WorkoutSessionExercise varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<WorkoutSessionExercise> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("WorkoutSessionExercise", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili antrenman oturumunun kimligi.
        builder.HasOne<WorkoutSession>()
            .WithMany()
            .HasForeignKey(x => x.WorkoutSessionId)
            .OnDelete(DeleteBehavior.Restrict);

        // Gerceklestirilen egzersizin kimligi.
        builder.HasOne<Exercise>()
            .WithMany()
            .HasForeignKey(x => x.ExerciseId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
