// <auto-generated>
// Bu dosya Claude tarafindan MerfitCustomerApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitCustomerApi.Domain.Entities;

namespace MerfitCustomerApi.Infrastructure.Configurations;

/// <summary>
/// WorkoutPlanExercise varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WorkoutPlanExerciseConfiguration : IEntityTypeConfiguration<WorkoutPlanExercise>
{
    /// <summary>
    /// WorkoutPlanExercise varligi icin tablo adi, birincil anahtar, alan kisitlari, index ve
    /// iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<WorkoutPlanExercise> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("WorkoutPlanExercise", "workout");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Onerilen sorgu senaryosu (WorkoutPlanDayId + Order) icin composite index.
        builder.HasIndex(x => new { x.WorkoutPlanDayId, x.Order });

        // Iliskiler (foreign key) yapilandirmasi.
        // Iliskili antrenman plani gununun kimligi. Gun silinirse (plan yeniden olusturulup
        // eski gunler temizlenirse) bu satirlar da silinmeli - Cascade.
        builder.HasOne<WorkoutPlanDay>()
            .WithMany()
            .HasForeignKey(x => x.WorkoutPlanDayId)
            .OnDelete(DeleteBehavior.Cascade);

        // Iliskili egzersizin kimligi. Katalogdaki bir Exercise silinemez/pasiflestirilir,
        // gecmis kisisel plan kayitlarini bozmamak icin Restrict.
        builder.HasOne<Exercise>()
            .WithMany()
            .HasForeignKey(x => x.ExerciseId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
